
[window]
opacity = 1.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
key = "Insert"
mods = "Control"
action = "Copy"

[[keyboard.bindings]]
key = "Insert"
mods = "Shift"
action = "Paste"

[general]
import = ["~/.config/alacritty/dank-theme.toml", "~/.config/alacritty/local.toml"]
