# --- Tabs ---
# New tab with Ctrl+Tab
map ctrl+tab new_tab

# (Optional but recommended) Navigate tabs
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab

# --- Clipboard ---
# Classic terminal copy/paste
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

map ctrl+h launch --location=hsplit
map ctrl+v launch --location=vsplit
